package com.cwi.matheus.pokeapp.base

const val SIMPLE_POKEMONS_PER_PAGE: Int = 9

const val EXTRAS_POKEMON_ID = "EXTRAS_POKEMON_ID"
const val EXTRAS_POKEMON_NAME = "EXTRAS_POKEMON_NAME"

const val SHARED_PREFERENCE_BIOMETRIC_NEEDED = "SHARED_PREFERENCE_BIOMETRIC_NEEDED"
const val SHARED_PREFERENCE_DARK_MODE = "SHARED_PREFERENCE_DARK_MODE"

const val POKEAPP_PREFERENCES = "PokeApp-Preferences"